Workio/Workio/Models/Report.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Workio.Models
{
    /// <summary>
    /// Class que representa uma denuncia
    /// </summary>
    public class Report
    {
        /// <summary>
        /// Id da denuncia
        /// </summary>
        [Key]
        public Guid Id { get; set; }
        /// <summary>
        /// Id do utilizador que denunciou
        /// </summary>
        public string? ReporterId { get; set; }
        /// <summary>
        /// Objeto de User que contem o utilizador que denunciou
        /// </summary>
        [ForeignKey("ReporterId")]
        public virtual User? Reporter { get; set; }
        /// <summary>
        /// Id da razão de denuncia
        /// </summary>
        public Guid? ReportReasonId { get; set; }
        /// <summary>
        /// Objeto de ReportReason que contem a razão da denuncia
        /// </summary>
        [ForeignKey("ReportReasonId")]
        public virtual ReportReason? ReportReason { get; set; }
        /// <summary>
        /// Objeto do tipo ReportStatus que demonstra o estado da denuncia
        /// </summary>
        public ReportStatus ReportStatus { get; set; } = ReportStatus.Pending;
        /// <summary>
        /// Descrição da denuncia
        /// </summary>
        [Required]
        [MaxLength(124)]
        public string Description { get; set; }
        /// <summary>
        /// Data da denuncia
        /// </summary>
        public DateTime Date { get; set; }

    }
}

Workio/Workio/Models/ReportReason.cs
using System.ComponentModel.DataAnnotations;

namespace Workio.Models
{
    /// <summary>
    /// Classe que representa as possiveis razões pré definidas para denuncias
    /// </summary>
    public class ReportReason
    {
        /// <summary>
        /// Id da razão
        /// </summary>
        [Key]
        public Guid? Id { get; set; }
        /// <summary>
        /// Razão em texto
        /// </summary>
        [Required]
        [MaxLength(64)]
        public string? Reason { get; set; }
        /// <summary>
        /// Representa o tipo de razão da denuncia, se é uma rasão para denuncia de utilizador,equipa ou evento
        /// </summary>
        public ReasonType ReasonType { get; set; }

    }
}

Workio/Workio/Controllers/AdminReportsController.cs
using MessagePack.Formatters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NToastNotify;
using System.Composition;
using System.Security.Claims;
using Workio.Models;
using Workio.Services;
using Workio.Services.Admin.Log;
using Workio.Services.Events;
using Workio.Services.Interfaces;
using Workio.Services.ReportServices;
using Workio.Services.Teams;
using Workio.Utils;

namespace Workio.Controllers
{
    /// <summary>
    /// Controlador para a gestão das denuncias por parte da administração
    /// </summary>
    [Authorize(Roles = "Admin, Mod")]
    public class AdminReportsController : Controller
    {
        /// <summary>
        /// Serviço para obter denuncias
        /// </summary>
        private readonly IReportReasonService _reportReasonService;
        /// <summary>
        /// Serviço para obter os utilizadores
        /// </summary>
        private readonly IUserService _userService;
        /// <summary>
        /// Serviço para obter as equipas
        /// </summary>
        private readonly ITeamsService _teamsService;
        /// <summary>
        /// Serviço para obter os eventos
        /// </summary>
        private readonly IEventsService _eventsService;
        /// <summary>
        /// Objeto do tipo ToastNotification para as notificações das ações realizadas
        /// </summary>
        private readonly IToastNotification _toastNotification;
        private readonly int _pageSize = 10;
        /// <summary>
        /// Objeto do tipo ToastNotification para as notificações das ações realizadas
        /// </summary>
        private readonly ILogsService _logsService;
        /// <summary>
        /// Objeto do tipo CommonLocalizationService para a tradução das notificações das ações
        /// </summary>
        private readonly CommonLocalizationService _localizationService;
        /// <summary>
        /// Construtor da classe.
        /// </summary>
        ///<param name="reportReasonService">Parametro de Serviço de denuncias para inicialização</param>
        ///
        public AdminReportsController(IReportReasonService reportReasonService, IUserService userService, ITeamsService teamsService, IEventsService eventsService, IToastNotification toastNotification, ILogsService logsService, CommonLocalizationService localizationService)
        {
            _reportReasonService = reportReasonService;
            _userService = userService;
            _teamsService = teamsService;
            _eventsService = eventsService;
            _toastNotification = toastNotification;
            _logsService = logsService;
            _localizationService = localizationService;
        }
        /// <summary>
        /// Metodo de encaminhamento para a página de visualização das denuncias
        /// </summary>
        public async Task<IActionResult> Reports()
        {
            ICollection<ReportUser> userReports = await _reportReasonService.GetUserReports();
            ICollection<ReportTeam> teamReports = await _reportReasonService.GetTeamReports();
            ICollection<ReportEvent> eventReports = await _reportReasonService.GetEventReports();
            ViewBag.UserReports = userReports;
            ViewBag.TeamReports = teamReports;
            ViewBag.EventReports = eventReports;
            return View();
        }
        /// <summary>
        /// Metodo responsavel por mostrar a página de detalhes de uma denuncia de utilizador
        /// </summary>
        ///<param name="id">Id da denuncia realizada ao utilizador</param>
        ///<returns>Retorna a view </returns>
        public async Task<IActionResult> DetailsUser(Guid id)
        {
            var report = await _reportReasonService.GetUserReport(id);
            if (report == null) { return NotFound(); }
            var allReports = await _reportReasonService.GetUserReports();
            ViewBag.OtherReports = from r in allReports where r.ReportedId == report.ReportedId && r.Id != report.Id select r;
            return View(report);
        }
        /// <summary>
        /// Metodo responsavel por mostrar a página de detalhes de uma denuncia de equipa
        /// </summary>
        ///<param name="id">Id da denuncia realizada à equipa</param>
        ///<returns>Retorna a view </returns>
        public async Task<IActionResult> DetailsTeam(Guid id)
        {
            var report = await _reportReasonService.GetTeamReport(id);
            if (report == null) { return NotFound(); }
            var OwnerId = report.ReportedTeam.OwnerId;
            var allReports = await _reportReasonService.GetTeamReports();
            ViewBag.OtherReports = from r in allReports where r.ReportedTeamId == report.ReportedTeamId && r.Id != report.Id select r;
            return View(report);
        }
        /// <summary>
        /// Metodo responsavel por mostrar a página de detalhes de uma denuncia de evento
        /// </summary>
        ///<param name="id">Id da denuncia realizada ao evento</param>
        ///<returns>Retorna a view </returns>
        public async Task<IActionResult> DetailsEvent(Guid id)
        {
            var report = await _reportReasonService.GetEventReport(id);
            if (report == null) { return NotFound(); }
            var allReports = await _reportReasonService.GetEventReports();
            ViewBag.OtherReports = from r in allReports where r.ReportedEventId == report.ReportedEventId && r.Id != report.Id select r;
            return View(report);
        }

        /// <summary>
        /// Metodo responsavel por mostrar a página de adicionar um nova razão de denuncia
        /// </summary>
        ///<param name="id">Id da denuncia realizada ao evento</param>
        ///<returns>Retorna a view </returns>
        public async Task<IActionResult> AddReportReason()
        {
            List<SelectListItem> reasonTypes = new List<SelectListItem>()
            {
                new SelectListItem { Value = ReasonType.User.ToString(), Text = TranslateReasonType(ReasonType.User) },
                new SelectListItem { Value = ReasonType.Team.ToString(), Text = TranslateReasonType(ReasonType.Team) },
                new SelectListItem { Value = ReasonType.Event.ToString(), Text = TranslateReasonType(ReasonType.Event) }
            };
            ViewBag.ReasonTypes = new SelectList(reasonTypes, "Value", "Text");
            return View();
        }


        /// <summary>
        /// Metodo responsavel por rejeitar uma denuncia de utilizador
        /// </summary>
        ///<param name="id">Id da denuncia</param>
        ///<param name="logModel">Modal com a justificação da ação para os logs</param>
        ///<returns>Retorna a view </returns>
        public async Task<IActionResult> RejectUserReport(Guid id, LogViewModel logModel)
        {
            if (id == null || logModel == null || string.IsNullOrEmpty(logModel.Description)) return NotFound();
            var result = await _reportReasonService.RejectUserReport(id);
            var user = await _userService.GetUser(CurrentUserId());
            if (result)
            {
                await _logsService.CreateUserActionLog(logModel.Description, user.Id.ToString(), Models.Admin.Logs.UserActionLogType.Other);
                _toastNotification.AddSuccessToastMessage(_localizationService.Get("ReportRejected"));
            }
            else
            {
                _toastNotification.AddErrorToastMessage(_localizationService.Get("FailedReportRejected"));
            }
            return RedirectToAction("Reports");
        }
        /// <summary>
        /// Metodo responsavel por rejeitar uma denuncia de equipa
        /// </summary>
        ///<param name="id">Id da denuncia</param>
        ///<param name="logModel">Modal com a justificação da ação para os logs</param>
        ///<returns>Retorna a view </returns>
        public async Task<IActionResult> RejectTeamReport(Guid id, LogViewModel logModel)
        {
            if (id == null || logModel == null || string.IsNullOrEmpty(logModel.Description)) return NotFound();
            var result = await _reportReasonService.RejectTeamReport(id);
            var user = await _userService.GetUser(CurrentUserId());
            var report = await _reportReasonService.GetTeamReport(id);
            if (result)
            {
                await _logsService.CreateTeamActionLog(logModel.Description, report.ReportedTeamId.ToString(), Models.Admin.Logs.TeamActionLogType.Other);
                _toastNotification.AddSuccessToastMessage(_localizationService.Get("ReportRejected"));
            }
            else
            {
                _toastNotification.AddErrorToastMessage(_localizationService.Get("FailedReportRejected"));
            }
            return RedirectToAction("Reports");
        }
        /// <summary>
        /// Metodo responsavel por rejeitar uma denuncia de evento
        /// </summary>
        ///<param name="id">Id da denuncia</param>
        ///<param name="logModel">Modal com a justificação da ação para os logs</param>
        ///<returns>Retorna a view </returns>
        public async Task<IActionResult> RejectEventReport(Guid id, LogViewModel logModel)
        {
            if (id == null || logModel == null || string.IsNullOrEmpty(logModel.Description)) return NotFound();
            var result = await _reportReasonService.RejectEventReport(id);
            var user = await _userService.GetUser(CurrentUserId());
            var report = await _reportReasonService.GetEventReport(id);
            if (result)
            {
                await _logsService.CreateEventActionLog(logModel.Description, report.ReportedEventId.ToString(), Models.Admin.Logs.EventActionLogType.Other);
                _toastNotification.AddSuccessToastMessage(_localizationService.Get("ReportRejected"));
            }
            else
            {

Workio/Workio/Views/AdminReports/AddReportReason.cshtml
@model Workio.Models.ReportReason


<h1>@localizer.Get("Add new Reason")</h1>



<hr />
<div class="row">
    <div class="col-md-8">
        <div class="row">
            <div class="col-md-12">
                <form id="myForm" method="post" class="needs-validation" novalidate>
                    <div class="row g-3 align-items-center mb-4">
                        <div class="col-md-12">
                            <label asp-for="ReasonType" class="form-label">
                                @localizer.Get("ReportType")
                            </label>
                            <select id="reasonType" asp-for="ReasonType" class="form-select" asp-items="ViewBag.ReasonTypes" required></select>
                            <span asp-validation-for="ReasonType" class="invalid-feedback">@localizer.Get("RequiredField")</span>
                        </div>
                    </div>
                    <div class="row g-3 align-items-center mb-4">
                        <div class="col-md-12">
                            <div class="form-outline">
                                <textarea id="reason" asp-for="Reason" name="Reason" rows="4" class="form-control" id="Reason" required></textarea>
                                <label typeof="textarea" asp-for="Reason" class="form-label">@localizer.Get("ReportReasonEnglish")</label>
                                <span asp-validation-for="Reason" class="invalid-feedback">@localizer.Get("RequiredField")</span>
                            </div>
                        </div>
                    </div>
                    <div class="row g-3 align-items-center mb-4">
                        <div class="col-md-12">
                            <div class="form-outline">
                                <textarea id="ReasonPortugues" name="ReasonPortugues" rows="4" class="form-control" required></textarea>
                                <label typeof="textarea" for="ReasonPortugues" class="form-label">@localizer.Get("ReportReasonPortuguese")</label>
                                <span validation-for="ReasonPortugues" class="invalid-feedback">@localizer.Get("RequiredField")</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-auto">
                            <div class="form-group">
                                <a class="btn btn-secondary mb-1" asp-action="ReportReasons" asp-controller="AdminReports">
                                    @localizer.Get("Cancel")
                                </a>
                            </div>
                        </div>
                        <div class="col-auto">
                            <div class="form-group">
                                <button type="submit" value="Submit" class="btn btn-primary">@localizer.Get("Submit")</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
        <!--Toast notification lib-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

        <script>

            document.addEventListener('DOMContentLoaded', function () {

                var myForm = document.getElementById('myForm');
                var logModal = document.getElementById('logModal');


                myForm.addEventListener('submit', function (event) {
                    event.preventDefault();
                    if (!myForm.checkValidity()) {
                        event.stopPropagation();
                        myForm.classList.add('was-validated');
                        return;
                    }
                    console.log("TESTE");

                    $('#logModal').modal('show');
                    logModal.addEventListener('click', function (event) {
                        event.preventDefault();

                        // Check if the modal submit button is clicked
                        if (event.target.id === 'submit-experience') {
                            var logForm = document.getElementById('logForm')
                            if (!logForm.checkValidity()) {
                                event.stopPropagation();
                                logForm.classList.add('was-validated')
                                return;
                            }

                            var formData = {
                                reasonType: $('#reasonType').val(),
                                reason: $('#reason').val(),
                                reasonPortugues: $('#ReasonPortugues').val(),
                                description: $('#Description').val()
                            };
                            $('#logModal').modal('hide');
                            $.ajax({
                                type: 'POST',
                                async: false,
                                url: '/AdminReports/AddReportReason',
                                data: JSON.stringify(formData),
                                contentType: 'application/json',
                                success: function (response) {
                                    // Handle success response from server
                                    console.log("success");
                                    window.location.href = "/AdminReports/ReportReasons?success=" + response.success + "&error=" + !response.success;

                                },
                                error: function (error) {
                                    // Handle error response from server
                                    console.log("error");
                                    window.location.href = "/AdminReports/ReportReasons?success=false&error=true";
                                }
                            });


                        }
                    });
                });
            });






        </script>
    }
</div>

Workio/Workio/Views/AdminReports/DetailsEvent.cshtml
@model ReportEvent;

<h1>@localizer.Get("EventReport")</h1>

<div class="container mt-5">
    <div class="row">
        <div class="col-md-12 col-12">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">@localizer.Get("EventInformation")</h3>
                    <div class="row">
                        <div class="col-sm-4">
                            <p>
                                @localizer.Get("Name")
                            </p>
                        </div>
                        <div class="col-sm-8">
                            <p>@Model.ReportedEvent.Title</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <p>
                                @localizer.Get("ReportReason")
                            </p>
                        </div>
                        <div class="col-sm-8">
                            <p>@Model.ReportReason.Reason</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <p>
                                @localizer.Get("Date")
                            </p>
                        </div>
                        <div class="col-sm-8">
                            <p>@Model.Date</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <p>
                                @localizer.Get("Status")
                            </p>
                        </div>
                        <div class="col-sm-8">
                            @if (Model.ReportStatus == ReportStatus.Pending)
                            {
                                <p style="color: orange">@localizer.Get("Pending")</p>
                            }
                            else if (Model.ReportStatus == ReportStatus.Accepted)

                            {
                                <p style="color: green">@localizer.Get("Accepted")</p>
                            }
                            else
                            {
                                <p style="color: red">@localizer.Get("Rejected")</p>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br />
    <div class="card" style="height: 150px;">
        <div class="card-body">
            <h3 class="card-title">@localizer.Get("Description")</h3>
            <div>
                @Model.Description
            </div>
        </div>
    </div>
</div>
<br />
@if (Model.ReportStatus == ReportStatus.Pending)
{
    <div class="text-center">
        <a href="#" class="btn btn-danger ms-auto" onclick="addActionToForm('/AdminReports/AcceptEventReport/@Model.Id')">@localizer.Get("Accept")</a>
        <a href="#" class="btn btn-primary ms-auto" onclick="addActionToForm('/AdminReports/RejectEventReport/@Model.Id')">@localizer.Get("Reject")</a>
    </div>
}
<h1>@localizer.Get("OtherReports")</h1>
@foreach (ReportEvent item in ViewBag.OtherReports)
{
    <a asp-controller="AdminReports" asp-action="DetailsEvent" asp-route-id=@item.Id>
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">@localizer.Get("EventInformation")</h4>
                <div class="row">
                    <div class="col-sm-4">
                        <p>@localizer.Get("Name")</p>
                    </div>
                    <div class="col-sm-8">
                        <p>@item.ReportedEvent.Title</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <p>@localizer.Get("ReportReason")</p>
                    </div>
                    <div class="col-sm-8">
                        <p>@item.ReportReason.Reason</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <p>@localizer.Get("Date"):</p>
                    </div>
                    <div class="col-sm-8">
                        <p>@item.Date</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <p>@localizer.Get("Status")</p>
                    </div>
                    <div class="col-sm-8">
                        @if (item.ReportStatus == ReportStatus.Pending)
                        {
                            <p style="color: orange">@localizer.Get("Pending")</p>
                        }
                        else if (item.ReportStatus == ReportStatus.Accepted)

                        {
                            <p style="color: green">@localizer.Get("Accepted")</p>
                        }
                        else
                        {
                            <p style="color: red">@localizer.Get("Rejected")</p>
                        }
                    </div>
                </div>
            </div>

        </div>
    </a>
}


</div>

Workio/Workio/Views/AdminReports/DetailsTeam.cshtml
@model ReportTeam;

<h1>@localizer.Get("TeamReport")</h1>

<div class="container mt-5">
    <div class="row">
        <div class="col-md-12 col-12">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">@localizer.Get("TeamInformation")</h3>
                    <div class="row">
                        <div class="col-sm-4">
                            <p>@localizer.Get("Name")</p>
                        </div>
                        <div class="col-sm-8">
                            <p>@Model.ReportedTeam.TeamName</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <p>@localizer.Get("ReportReason")</p>
                        </div>
                        <div class="col-sm-8">
                            <p>@Model.ReportReason.Reason</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <p>@localizer.Get("Date")</p>
                        </div>
                        <div class="col-sm-8">
                            <p>@Model.Date</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <p>@localizer.Get("Status")</p>
                        </div>
                        <div class="col-sm-8">
                            @if (Model.ReportStatus == ReportStatus.Pending)
                            {
                                <p style="color: orange">@localizer.Get("Pending")</p>
                            }
                            else if (Model.ReportStatus == ReportStatus.Accepted)

                            {
                                <p style="color: green">@localizer.Get("Accepted")</p>
                            }
                            else
                            {
                                <p style="color: red">@localizer.Get("Rejected")</p>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br />
    <div class="card" style="height: 150px;">
        <div class="card-body">
            <h3 class="card-title">@localizer.Get("Description")</h3>
            <div>
                @Model.Description
            </div>
        </div>
    </div>
</div>
<br />
@if (Model.ReportStatus == ReportStatus.Pending)
{
    <div class="text-center">
        <a href="#" class="btn btn-danger ms-auto" onclick="addActionToForm('/AdminReports/AcceptTeamReport/@Model.Id')">@localizer.Get("Accept")</a>
        <a href="#" class="btn btn-primary ms-auto" onclick="addActionToForm('/AdminReports/RejectTeamReport/@Model.Id')">@localizer.Get("Reject")</a>
    </div>
}
<h1>@localizer.Get("OtherReports")</h1>
@foreach (ReportTeam item in ViewBag.OtherReports)
{
    <a asp-controller="AdminReports" asp-action="DetailsTeam" asp-route-id=@item.Id>
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">@localizer.Get("TeamInformation")</h4>
                <div class="row">
                    <div class="col-sm-4">
                        <p>@localizer.Get("Name")</p>
                    </div>
                    <div class="col-sm-8">
                        <p>@item.ReportedTeam.TeamName</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <p>@localizer.Get("ReportReason")</p>
                    </div>
                    <div class="col-sm-8">
                        <p>@item.ReportReason.Reason</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <p>@localizer.Get("Date")</p>
                    </div>
                    <div class="col-sm-8">
                        <p>@item.Date</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <p>@localizer.Get("Status")</p>
                    </div>
                    <div class="col-sm-8">
                        @if (item.ReportStatus == ReportStatus.Pending)
                        {
                            <p style="color: orange">@localizer.Get("Pending")</p>
                        }
                        else if (item.ReportStatus == ReportStatus.Accepted)

                        {
                            <p style="color: green">@localizer.Get("Accepted")</p>
                        }
                        else
                        {
                            <p style="color: red">@localizer.Get("Rejected")</p>
                        }
                    </div>
                </div>
            </div>

        </div>
    </a>
}


</div>

Workio/Workio/Views/AdminReports/ReportReasons.cshtml
@{
    var currentCulture = Thread.CurrentThread.CurrentCulture.Name;
}
<link href="/lib/DataTables/datatables.min.css" rel="stylesheet" />

<style>

    #reportReasonsTable td {
        vertical-align: middle;
    }

    table {
        width: 100% !important;
    }

</style>

<a asp-action="AddReportReason" asp-controller="AdminReports" class="btn btn-primary mb-1">@localizer.Get("AddNewReportReason")</a>


<table id="reportReasonsTable" class="table">
    <thead>
        <tr>
            <th>
                @localizer.Get("Reason")

            </th>
            <th>
                @localizer.Get("Type")

            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>




@section Scripts {
    <script src="/lib/DataTables/datatables.min.js"></script>
    <script>
        /*$(document).ready(function () {
            $("#myTable").DataTable({
                paging: true,--
                responsive: true,
            });
        });*/
        var localizationUrl = '@currentCulture' == 'pt' ? '//cdn.datatables.net/plug-ins/1.13.4/i18n/pt-PT.json' : ''
        $(document).ready(function () {
            $('#reportReasonsTable').DataTable({
                language: {
                    url: localizationUrl,
                },
                searching: false,
                responsive: true,
                processing: true,
                serverSide: true,
                ordering: false,
                ajax: {
                    url: '/AdminReports/GetDataReportReasons',
                    type: 'GET',
                    data: function (d) {
                        // Add any required parameters to the request.
                        d.searchValue = $('#usersActionLogDataTable_filter input').val();
                        d.sortColumn = $('#sortColumnSelect').val();
                        d.sortDirection = $('#sortDirectionSelect').val();
                    }
                },
                columns: [
                    { data: 'reason' },
                    { data: 'reasonType' },
                    {
                        data: "id",
                        render: function (dataField) {
                            return '<a href="#" onclick="addActionToForm(\'/AdminReports/RemoveReportReason/' + dataField + '\')">@localizer.Get("Remove")</a>';
                        }

                    }
                ]
            });
        });

    </script>
}